# Generated by Django 5.2.4 on 2025-07-23 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='shipment_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='shipment_status',
            new_name='status',
        ),
    ]
